### ISSUE TITLE
 Ajustes de Conformidade no Projeto

### ISSUE THREAD

**Issue by Lorraine-Olegario** [juliodeoliveira/MVC-project#1]
### Adicionar vendor ao .gitignore:
- A pasta vendor não deve ser versionada no repositório. Adicione vendor/ ao arquivo .gitignore para evitar que ela seja incluída nos commits.

### Nome das Classes:
- Todas as classes devem começar com a letra maiúscula. Por favor, revise todas as classes e corrija os nomes conforme necessário.

### Namespace:
- Altere o namespace para App em todos os arquivos de classes.

### Estilo de Métodos:

- Especifique sempre o tipo de retorno dos métodos e o tipo dos parâmetros. Exemplo:
- Sempre utilize um espaço entre if e a abertura do parênteses.
- Os métodos devem ser formatados com a chave de abertura na linha seguinte ao nome do método. Exemplo:
```
public function exemplo()
{
    // código
}
```

**Comment by juliodeoliveira** [comment]
Foram feitas todas as alterações necessárias para que o código do projeto seja mais legível e que ele se enquadre às regras de boas práticas
